spring:
  jmx:
    default-domain: mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/testtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /
  port: 8981

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo1.demo1.entity

logging:
  level:
    com.demo1.demo1.mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
